### ISSUE TITLE
Creare bozza mappa sardegna con sample di dati

### ISSUE THREAD

**Issue by nelsonmau** [ondata/confiscatibene-sardegna#1]
i dati si trovano sullo spreadsheet a questo indirizzo

https://docs.google.com/spreadsheets/d/1okQL45mY3n4_AvvUItN6b6YJe92uWh9WwSiCmknOScY/edit?ts=5a183658#gid=957389692

**Comment by elimulas** [comment]
a questo indirizzo ho raccolto tutte le storie sui comuni, che includono riuso, non riuso, impatto.
https://docs.google.com/spreadsheets/d/1c84JqDLV3ZD06tSNofNd6k5VPPzTfRPIa9JgXnmaa-w/edit?usp=sharing
Sorge un problema: abbiamo scritto storie uniche per comune e non divise per bene, perché in molti casi la notizia non sta nel singolo bene ma piuttosto nella confisca o nell'impatto e avremmo dovuto ripeterla sempre uguale. A questo punto però, come abbinare le storie alla georeferenziazione? 
due le opzioni che potremmo considerare: 
1) georeferenziare il municipio o il centro città e raccontare un'unica storia per comune;
2) separare le storie in a) impatto o confisca, da abbinare ad un luogo x (es. municipio); b) tante storie quanti beni da abbinare ai singoli beni da mappare.

Come procediamo?

Avremmo anche bisogno di un feedback sulle storie raccontate prima che vengano pubblicate.

Grazie mille!

**Comment by nelsonmau** [comment]
ciao @elimulas e grazie del sempre ottimo lavoro intanto!

direi che:

* queste sedici storie saranno dei puntini/marker sulla mappa. L'utente clicca sul marker > si apre una finestra > esce la scheda del comune con una descrizione complessiva della situazione (quella inserita da voi). 
* i testi che state inserendo in #4 invece li mettiamo in pagina. 

ovviamente come dici tu c'è tutto il tema delle immagini (e dei video!) che è importante e al momento non ne abbiamo. 

quando le avete raccolte fammi un fischio e ti dico come procedere

Intanto comincio a impostare la pagina complessiva e la mappa prima di capodanno

**Comment by nelsonmau** [comment]
fatto

**Comment by nelsonmau** [comment]
@elimulas nella tabella

https://docs.google.com/spreadsheets/d/1xnVi1UjRAd50idDmXtKcYv-UxNWAE-rHL8qJeF3ef5o/edit#gid=0

occorre aggiungere delle nuove colonne, io ne ho aggiunta una con nome `BeniConfiscati` che indica il totale nel beni nel comune.

Occorre anche aggiungere:

* beni riusati
* numero giorni dopo i quali è arrivata la risposta al FOIA

ti vengono in mente altre colonne che possiamo aggiungere?

grazie

**Comment by elimulas** [comment]
Ciao @nelsonmau 
Non riesco a visualizzare il file, ti ho mandato la richiesta d'accesso.

Grazie mille

**Comment by nelsonmau** [comment]
fatto

**Comment by elimulas** [comment]
@nelsonmau, dati aggiornati, ho aggiunto la colonna per i beni riutilizzati ma non so come farlo apparire sulla mappa.

Altra cosa: nelle storie di riuso ci sono da mettere dei link, come si fa?

Grazie, vado a dormire!

**Comment by nelsonmau** [comment]
Ciao @elimulas 

* I dati ora si vedono sulle schede
* i video caricateli tutti su un vostro canale youtube e poi mettete il link nella tabella togliendo l'indirizzo di google/dropbox che c'è adesso
* le immagine salvale tutte in [questa cartella](https://github.com/ondata/confiscatibene-sardegna/tree/master/img): se vedi, in alto a destra c'è scritto `Upload files` che puoi cliccare per caricare. 

fammi sapere quando ok

**Comment by elimulas** [comment]
Done!
Puoi controllare se va tutto bene per favore?

**Comment by nelsonmau** [comment]
meglio

controlli tu adesso?

**Comment by elimulas** [comment]
Continuo a non vedere le foto nella mappa, come mai?
Nelle storie di riuso ci sarebbero dei link "leggi", come li inserisco?

**Comment by nelsonmau** [comment]
adesso?

**Comment by nelsonmau** [comment]
riguardo ai link "leggi": inseriscili nel testo nel google spreadsheet

**Comment by nelsonmau** [comment]
fatto, chiudo!
