### ISSUE TITLE
ridefinire il tempo di risposta alla richiesta di riesame - index

### ISSUE THREAD

**Issue by giuragu** [ondata/confiscatibene-sardegna#12]
Ciao @elimulas 
ho notato un piccolo errore in index dove leggo che per la richiesta di riesame il tempo entro cui la PA deve rispondere è di 10 giorni quando in realtà sarebbero 20 giorni. Sono certo sia un refuso.
In bocca al lupo per tutto :)

**Comment by elimulas** [comment]
@giuragu grazie mille per il controllo e per l'in bocca al lupo, 
speriamo di fare una buona presentazione domani!

Correggo subito il refuso.

**Comment by giuragu** [comment]
Ottimo! Chiudo.
