### ISSUE TITLE
sistemare copyright e footer

### ISSUE THREAD

**Issue by nelsonmau** [ondata/confiscatibene-sardegna#15]
Confiscatibene.it è un progetto di Ondata.it - Tutti i contenuti sono sotto la licenza CC-By SA 4.0. 
Invia segnalazioni di errori o richieste di informazioni a: info@confiscatibene.it

**Comment by elimulas** [comment]
Fatto, però @nelsonmau puoi verificare se va bene per favore?
Thanks!

**Comment by nelsonmau** [comment]
metterei entrambe le frasi all'interno dello sesso tag (mentre ora hai messo "per ogni informazione..." in basso) in modo che sia formattati alla stessa maniera (font, posizione...)

per andare accapo usa '<br>', info qui https://www.w3schools.com/tags/tag_br.asp 

:-)

**Comment by elimulas** [comment]
Fatto, chiudo!
