### ISSUE TITLE
link nelle storie di riuso

### ISSUE THREAD

**Issue by elimulas** [ondata/confiscatibene-sardegna#19]
ciao @nelsonmau 
potresti spiegarmi come attivare i link dentro le storie di riuso (nella mappa)? Ho visto la funzione "aggiungi link" nello spreadsheets ma non riesco ad utilizzarlo. Per comodità ho temporaneamente messo i link per esteso all'interno dei testi.
Grazie!!

**Comment by nelsonmau** [comment]
@elimulas yep!

semplicemente mettendo il tag html <a> all'interno del testo.
Quindi ad esempio, questo:

> Era  il 1998 quando a Matilde Ciarlante, cassiera della mafia insieme al marito Pino Cillari (leggi http://ricerca.repubblica.it/repubblica/archivio/repubblica/1998/07/02/cassieri-della-mala-con-40-miliardi.html), fu sequestrato un impero di 40 miliardi di lire, tra cui 8 ettari di terreno con un fabbricato rurale a Cannigione, frazione turistica di

diventa

> Era il 1998 quando a Matilde Ciarlante, cassiera della mafia insieme al marito Pino Cillari (`<a href="http://ricerca.repubblica.it/repubblica/archivio/repubblica/1998/07/02/cassieri-della-mala-con-40-miliardi.html" target="_blank">leggi</a>`), fu sequestrato un impero di 40 miliardi di lire, tra cui 8 ettari di terreno con un fabbricato rurale a Cannigione, frazione turistica di

**Comment by elimulas** [comment]
Done! Thank you so much!!
