### ISSUE TITLE
Verificare comunicati stampa

### ISSUE THREAD

**Issue by nelsonmau** [ondata/confiscatibene-sardegna#2]
eccoli qui

https://docs.google.com/document/d/1XCHi1g9X0AZocQ_mrJyYFrAMgaGU-o1BB9qSJFB5b5o/edit?ts=5a185266

@elimulas: mi avvisi quando ci sono tutti?
grazie

**Comment by elimulas** [comment]
Pronti! Ci sono tutti.

**Comment by nelsonmau** [comment]
ho verificato i comunicati e vi mando un feedback generale su questi e gli altri testi
