### ISSUE TITLE
Georeferenziazione

### ISSUE THREAD

**Issue by elimulas** [ondata/confiscatibene-sardegna#21]
I puntini di Olbia, Golfo Aranci e Loiri Porto San Paolo non sono localizzati nei comuni

**Comment by aborruso** [comment]
@elimulas per favore mi rispondi [qui](http://partecipa.confiscatibene.it/t/monitoraggio-beni-confiscati-in-sardegna-un-progetto-universitario/132/39?u=aborruso) e io poi ti rispondo a questa issue.

Grazie

**Comment by elimulas** [comment]
@aborruso scusami, non so perché la mia casella di posta non mi ha mostrato le ultime email di Partecipa... 
Ho appena risposto!

**Comment by elimulas** [comment]
Risolto.
