### ISSUE TITLE
Link ai social e github

### ISSUE THREAD

**Issue by elimulas** [ondata/confiscatibene-sardegna#22]
La prof chiede se sia necessario il link a github e in generale, per tutte le icone nel footer, se sia possibile modificare in modo che rinviino a nuove schede anziché restare nella stessa.
@nelsonmau che dici?

**Comment by nelsonmau** [comment]
ciao @elimulas, sì e buona norma metterli sempre.

per fare in modo che si aprano in una nuova pagina, occorre per ogni link aggiungere l'attributo `target`

così ad esempio, questo:

`<a href="http://twitter.com/confiscatibene">`

deve diventare

`<a href="http://twitter.com/confiscatibene" target="_blank">`

modifichi tu? 
grazie! :-)

**Comment by elimulas** [comment]
Fatto!!!!! Da settimane copiavo tutto il tag per i link senza aver capito che target serviva per questo!
Learning just by doing

Chiudo!

**Comment by nelsonmau** [comment]
@elimulas qualiasi dubbio generalmente trova risposta su questo sito https://www.w3schools.com/
