### ISSUE TITLE
conflitto git

### ISSUE THREAD

**Issue by nelsonmau** [ondata/confiscatibene-sardegna#24]
cara @elimulas, 

hai creato il tuo primo "conflitto git" infatti ora sul sito si vede questo

```
<<<<<<< HEAD
Inchiesta degli studenti del corso di Comunicazione e partecipazione politica dell'Università di Sassari =======
Inchiesta degli studenti del corso di Comunicazione e partecipazione politica dell'Università di Sassari 
Ultimo aggiornamento dei dati: 28/01/2018 >>>>>>> 42ae0a6e038dbffbeb5e776825242ae0c9aa9dad 

```

io sono uno specialista di conflitti git, nonostante il mio mentore sia @aborruso :-)

per capire cos'è successo, sei costretta a dare una lettura a un approfondimento su cos'è git (la tecnologia che sta alla base di github). Ti segnalo [questa lettura](https://www.linuxtrent.it/sites/default/files/Comprendere%20Git%20concettualmente.pdf): basta leggere i primi tre o quattro capitoli... quando diventa incomprensibile del tutto, fermati :-)

**Comment by nelsonmau** [comment]
uh uh che ridere: chiedo sorry, ma il conflitto era colpa mia e ho sistemato :-)

**Comment by elimulas** [comment]
ahahahah effettivamente l'altro giorno ho visto appariva <<<<<<<HEAD ecc. 
in quell'occasione, senza leggere i capitoli (nemmeno i comprensibili) ho semplicemente cancellato da index.thml tutto ciò che era extra! Forse non so quello che ho fatto :-D

**Comment by nelsonmau** [comment]
ma c'è un senso in tutto ciò, dai un'occhiata al libro

poi nel weekend chiediamo ad @aborruso di farci un riassunto (lui ne sa a palate <3 )

**Comment by elimulas** [comment]
Dopo l'esame di martedì mi ci dedicherò!! ;)
Passo e chiudo!
