### ISSUE TITLE
Iscrizioni su github e nickname utenti 

### ISSUE THREAD

**Issue by nelsonmau** [ondata/confiscatibene-sardegna#3]
@elimulas please, quando colleghi e colleghe si iscriveranno su github, puoi dire loro di rispondere qui scrivendo il loro nome utente?

grazie!

**Comment by elimulas** [comment]
Ciao!
Credo che saranno al completo non prima di domani, oggi alcune lavorano al
bar!

Il 25 nov 2017 5:01 PM, "Andrea Nelson Mauro" <notifications@github.com> ha
scritto:

**Comment by stefanosanna1** [comment]
@nelsonmau Sono Stefano, il mio nick è stefanosanna1

**Comment by claudiaca93** [comment]
@nelsonmau Sono Claudia, il mio nick è claudiaca93

**Comment by lauradettori** [comment]
@nelsonmau Sono Laura, il mio nick è lauradettori

**Comment by Valeriad11** [comment]
@nelsonmau  Sono Valeria, il mio nick è valeriad11

**Comment by SaraDangelo** [comment]
Sono Sara, il mio nick é SaraDangelo

**Comment by mattiaserra90** [comment]
Sono Mattia. Il mio nickname è mattiaserra90

**Comment by lauraiannelli** [comment]
mi sono iscritta anch'io.  Il nick è: lauraiannelli

**Comment by Robertaorru** [comment]
scusate il ritardo. mi sono iscritta ieri pomeriggio. Il nick è robertaorru

**Comment by nelsonmau** [comment]
grazie a todos, @elimulas possiamo cominciare a creare il sito?

**Comment by elimulas** [comment]
Ciao @nelsonmau , possiamo cominciare! Ho raccolto il materiale (solo i testi, aggiungerò appena possibile alcune immagini) nei file a cui ho messo i link negli altri issues.
Grazie mille :)

**Comment by nelsonmau** [comment]
grazie a @elimulas e a todos,

trovate la prima bozza online qui https://ondata.github.io/confiscatibene-sardegna/
