### ISSUE TITLE
Long/lat da dataset openras

### ISSUE THREAD

**Issue by elimulas** [ondata/confiscatibene-sardegna#30]
Ciao @aborruso e @nelsonmau 
Ho modificato le coordinate, ma c'erano due colonne per ognuna: long (che ho modificato) e long originale: potete dirmi se ho fatto giusto?
Ho messo anche il link al dataset come fonte nei metadati: giusto?

per comodità vi metto il link 
https://docs.google.com/spreadsheets/d/1xnVi1UjRAd50idDmXtKcYv-UxNWAE-rHL8qJeF3ef5o/edit#gid=241192064

**Comment by aborruso** [comment]
@elimulas non va bene. Aggiorno io e ti avviso

**Comment by elimulas** [comment]
Grazie... 
:(

**Comment by aborruso** [comment]
@elimulas c'erano dei numeri "pazzi" (vedi sotto).

Ho inserito le coordinate di @nelsonmau 

![immagine](https://user-images.githubusercontent.com/30607/35705856-fb46223e-07a3-11e8-9ad1-95ba0e78d5c4.png)
