### ISSUE TITLE
Schema pagina: titoli e oggetti da inserire

### ISSUE THREAD

**Issue by nelsonmau** [ondata/confiscatibene-sardegna#4]
@elimulas mi scrivi qui please i titoli provvisori dei capitoletti dai quali sarà composta la pagina?)
grazie!

**Comment by elimulas** [comment]
1.  I beni confiscati alle mafie
2.  Sardegna: isola felice? (testo + mappa con storie del riuso all'interno)
3.  Storie di riuso (altro capitolo o solo all'interno della mappa?)
4.  Alcune idee di riuso 
5.  Il nostro progetto

**Comment by nelsonmau** [comment]
ci vuole sicuramente un capitoletto per fare un focus sul FOIA: cosa avete fatto e che riscrontri avete avuto

anyway, cominciamo da qui

**Comment by nelsonmau** [comment]
abbiamo intanto un link provvisorio e funzionante al sito 
https://ondata.github.io/confiscatibene-sardegna/

**Comment by elimulas** [comment]
Sono contenta per il link!! 
Il discorso foia lo abbiamo immaginato come testo che spiega cosa sia e l'impatto generato + link a tabella su gdrive. 
Tabelle ne abbiamo due, quella di riepilogo delle richieste e risposte e quella con le norme sull'amm. trasparente ecc. E lo avevamo ipotizzato come parte della sezione "il ns progetto". 
Se invece fosse meglio dargli più risalto potremmo fare un capitolo dopo " isola felice".

**Comment by elimulas** [comment]
Ciao Andrea :)
i contenuti per il sito stanno prendendo forma e li sto raccogliendo in questo file:

https://docs.google.com/spreadsheets/d/1JRXDp-9d8pv6tov5e_C1TuuD4doyY0udeR3LZ3GVdi8/edit?usp=sharing

come vedrai manca il focus su foia (abbiamo però una tabella dettagliata su dropbox) e il nostro progetto che vorremmo raccontare attraverso un video.

**Comment by nelsonmau** [comment]
abbiamo tutto online

chiudo qui
