### ISSUE TITLE
Materiale da inserire nel sito

### ISSUE THREAD

**Issue by elimulas** [ondata/confiscatibene-sardegna#6]
Inserire nella mappa: 
1) interviste (dolianova e iglesias)
2) foto/video (alghero, dorgali. gergei, golfo aranci, sassari)
  
https://www.dropbox.com/home/Inchiesta%20open%20data%20journalism%20%40Lavoro%20di%20gruppo_COM%20e%20PART%20POL%2017_18/Materiale%20per%20il%20sito

**Comment by elimulas** [comment]
Incollo qui il link al documento con tutti i file e chiedo ai miei colleghi di fare tutte le modifiche che troveranno nei commenti.

https://docs.google.com/document/d/1xcwzYdX9Nxc6NJjGht58-H15iaQMhvcom6O-cIn6dWo/edit?usp=sharing

Ho inserito tutto ciò che avevo a disposizione e stupidamente ho esportato tutte le tabelle in g.docs senza pensare che potevamo condividere direttamente da dropbox. (ci sono link a dropbox solo per le interviste e il pdf best practices, quando finalmente ho avuto l'illuminazione).

Colleghi, avvisatemi quando avete terminato, avete tempo per apportare le modifiche fino a martedì. 
Ps: accertatevi che ogni testo sia tra le 1000 e 2000 battute spazi inclusi.

Buon weekend a tutti voi e grazie.

**Comment by elimulas** [comment]
Ultima cosa: inserire in fondo a "il progetto" questo video https://www.youtube.com/watch?v=vr5eIex3BZc

@nelsonmau che tag devo usare?

**Comment by nelsonmau** [comment]
si tratta di embeddare una pagine web che sta su un altro sito

solitamente si usa `<iframe src="...URL"></iframe>`

spesso i servizi (youtube, slideshare, etc) ti danno dei codici di embedding che devi solo copia-incollare dentro la tua pagina html (in questo caso è così)

chiudo!
